version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    environment:
      - PORT=5000
    volumes:
      - ./src:/usr/src/app
    ports:
      - "8000:5000"

volumes:
  custom-volume-name:
    driver: local